// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SGR.Api.Data;

#nullable disable

namespace SGR.Api.Migrations.Tenant
{
    [DbContext(typeof(TenantDbContext))]
    partial class TenantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SGR.Api.Models.Tenant.Entities.CanalVenda", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("TaxaPercentualPadrao")
                        .HasColumnType("numeric");

                    b.Property<string>("UsuarioAtualizacao")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCriacao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("CanalVenda", (string)null);
                });

            modelBuilder.Entity("SGR.Api.Models.Tenant.Entities.CategoriaInsumo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioAtualizacao")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCriacao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("CategoriaInsumo", (string)null);
                });

            modelBuilder.Entity("SGR.Api.Models.Tenant.Entities.CategoriaReceita", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioAtualizacao")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCriacao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CategoriaReceita", (string)null);
                });

            modelBuilder.Entity("SGR.Api.Models.Tenant.Entities.FichaTecnica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoriaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<decimal>("CustoPorUnidade")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CustoTotal")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoComercial")
                        .HasColumnType("text");

                    b.Property<char?>("ICOperador")
                        .HasColumnType("character(1)");

                    b.Property<int?>("ICValor")
                        .HasColumnType("integer");

                    b.Property<int?>("IPCValor")
                        .HasColumnType("integer");


                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MargemAlvoPercentual")
                        .HasColumnType("numeric");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PorcaoVendaQuantidade")
                        .HasColumnType("numeric");

                    b.Property<long?>("PorcaoVendaUnidadeMedidaId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("PrecoSugeridoVenda")
                        .HasColumnType("numeric");

                    b.Property<long?>("ReceitaPrincipalId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("RendimentoFinal")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RendimentoPorcoesNumero")
                        .HasColumnType("numeric");

                    b.Property<int?>("TempoPreparo")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioAtualizacao")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCriacao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("PorcaoVendaUnidadeMedidaId");

                    b.HasIndex("ReceitaPrincipalId");

                    b.ToTable("FichaTecnica", (string)null);
                });

            modelBuilder.Entity("SGR.Api.Models.Tenant.Entities.FichaTecnicaCanal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("CanalVendaId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("ComissaoPercentual")
                        .HasColumnType("numeric");

                    b.Property<long>("FichaTecnicaId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MargemCalculadaPercentual")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Multiplicador")
                        .HasColumnType("numeric");

                    b.Property<string>("NomeExibicao")
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("TaxaPercentual")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CanalVendaId");

                    b.HasIndex("FichaTecnicaId");

                    b.ToTable("FichaTecnicaCanal", (string)null);
                });

            modelBuilder.Entity("SGR.Api.Models.Tenant.Entities.FichaTecnicaItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ExibirComoQB")
                        .HasColumnType("boolean");

                    b.Property<long>("FichaTecnicaId")
                        .HasColumnType("bigint");

                    b.Property<long?>("InsumoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric");

                    b.Property<long?>("ReceitaId")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoItem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UnidadeMedidaId")
                        .HasColumnType("bigint");

                    b.Property<string>("UsuarioAtualizacao")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCriacao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FichaTecnicaId");

                    b.HasIndex("InsumoId");

                    b.HasIndex("ReceitaId");

                    b.HasIndex("UnidadeMedidaId");

                    b.ToTable("FichaTecnicaItem", null, t =>
                        {
                            t.HasCheckConstraint("CK_FichaTecnicaItem_TipoItem", "(\"TipoItem\" = 'Receita' AND \"ReceitaId\" IS NOT NULL AND \"InsumoId\" IS NULL) OR (\"TipoItem\" = 'Insumo' AND \"InsumoId\" IS NOT NULL AND \"ReceitaId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("SGR.Api.Models.Tenant.Entities.Insumo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoriaId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CustoUnitario")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<decimal>("FatorCorrecao")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("IPCValor")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PathImagem")
                        .HasColumnType("text");

                    b.Property<decimal>("QuantidadePorEmbalagem")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("UnidadesPorEmbalagem")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PesoPorUnidade")
                        .HasColumnType("numeric");

                    b.Property<long>("UnidadeCompraId")
                        .HasColumnType("bigint");

                    b.Property<string>("UsuarioAtualizacao")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCriacao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UnidadeCompraId");

                    b.ToTable("Insumo", (string)null);
                });

            modelBuilder.Entity("SGR.Api.Models.Tenant.Entities.Receita", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoriaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Conservacao")
                        .HasColumnType("text");

                    b.Property<decimal>("CustoPorPorcao")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CustoTotal")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<decimal>("FatorRendimento")
                        .HasColumnType("numeric");

                    b.Property<string>("InstrucoesEmpratamento")
                        .HasColumnType("text");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PathImagem")
                        .HasColumnType("text");

                    b.Property<decimal?>("PesoPorPorcao")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Rendimento")
                        .HasColumnType("numeric");

                    b.Property<int?>("TempoPreparo")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioAtualizacao")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCriacao")
                        .HasColumnType("text");

                    b.Property<string>("Versao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Receita", (string)null);
                });

            modelBuilder.Entity("SGR.Api.Models.Tenant.Entities.ReceitaItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("ExibirComoQB")
                        .HasColumnType("boolean");

                    b.Property<long>("InsumoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric");

                    b.Property<long>("ReceitaId")
                        .HasColumnType("bigint");

                    b.Property<long>("UnidadeMedidaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InsumoId");

                    b.HasIndex("ReceitaId");

                    b.HasIndex("UnidadeMedidaId");

                    b.ToTable("ReceitaItem", (string)null);
                });

            modelBuilder.Entity("SGR.Api.Models.Tenant.Entities.TenantPerfil", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioAtualizacao")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCriacao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Perfil", (string)null);
                });

            modelBuilder.Entity("SGR.Api.Models.Tenant.Entities.TenantUsuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PathImagem")
                        .HasColumnType("text");

                    b.Property<long>("PerfilId")
                        .HasColumnType("bigint");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioAtualizacao")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCriacao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PerfilId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("SGR.Api.Models.Tenant.Entities.UnidadeMedida", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioAtualizacao")
                        .HasColumnType("text");

                    b.Property<string>("UsuarioCriacao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.HasIndex("Sigla")
                        .IsUnique();

                    b.ToTable("UnidadeMedida", (string)null);
                });

            modelBuilder.Entity("SGR.Api.Models.Tenant.Entities.FichaTecnica", b =>
                {
                    b.HasOne("SGR.Api.Models.Tenant.Entities.CategoriaReceita", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGR.Api.Models.Tenant.Entities.UnidadeMedida", "PorcaoVendaUnidadeMedida")
                        .WithMany()
                        .HasForeignKey("PorcaoVendaUnidadeMedidaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SGR.Api.Models.Tenant.Entities.Receita", "ReceitaPrincipal")
                        .WithMany()
                        .HasForeignKey("ReceitaPrincipalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Categoria");

                    b.Navigation("PorcaoVendaUnidadeMedida");

                    b.Navigation("ReceitaPrincipal");
                });

            modelBuilder.Entity("SGR.Api.Models.Tenant.Entities.FichaTecnicaCanal", b =>
                {
                    b.HasOne("SGR.Api.Models.Tenant.Entities.CanalVenda", "CanalVenda")
                        .WithMany("FichaTecnicaCanais")
                        .HasForeignKey("CanalVendaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SGR.Api.Models.Tenant.Entities.FichaTecnica", "FichaTecnica")
                        .WithMany("Canais")
                        .HasForeignKey("FichaTecnicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanalVenda");

                    b.Navigation("FichaTecnica");
                });

            modelBuilder.Entity("SGR.Api.Models.Tenant.Entities.FichaTecnicaItem", b =>
                {
                    b.HasOne("SGR.Api.Models.Tenant.Entities.FichaTecnica", "FichaTecnica")
                        .WithMany("Itens")
                        .HasForeignKey("FichaTecnicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGR.Api.Models.Tenant.Entities.Insumo", "Insumo")
                        .WithMany()
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SGR.Api.Models.Tenant.Entities.Receita", "Receita")
                        .WithMany()
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SGR.Api.Models.Tenant.Entities.UnidadeMedida", "UnidadeMedida")
                        .WithMany()
                        .HasForeignKey("UnidadeMedidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FichaTecnica");

                    b.Navigation("Insumo");

                    b.Navigation("Receita");

                    b.Navigation("UnidadeMedida");
                });

            modelBuilder.Entity("SGR.Api.Models.Tenant.Entities.Insumo", b =>
                {
                    b.HasOne("SGR.Api.Models.Tenant.Entities.CategoriaInsumo", "Categoria")
                        .WithMany("Insumos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGR.Api.Models.Tenant.Entities.UnidadeMedida", "UnidadeCompra")
                        .WithMany()
                        .HasForeignKey("UnidadeCompraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("UnidadeCompra");
                });

            modelBuilder.Entity("SGR.Api.Models.Tenant.Entities.Receita", b =>
                {
                    b.HasOne("SGR.Api.Models.Tenant.Entities.CategoriaReceita", "Categoria")
                        .WithMany("Receitas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SGR.Api.Models.Tenant.Entities.ReceitaItem", b =>
                {
                    b.HasOne("SGR.Api.Models.Tenant.Entities.Insumo", "Insumo")
                        .WithMany()
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGR.Api.Models.Tenant.Entities.Receita", "Receita")
                        .WithMany("Itens")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SGR.Api.Models.Tenant.Entities.UnidadeMedida", "UnidadeMedida")
                        .WithMany()
                        .HasForeignKey("UnidadeMedidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Insumo");

                    b.Navigation("Receita");

                    b.Navigation("UnidadeMedida");
                });

            modelBuilder.Entity("SGR.Api.Models.Tenant.Entities.TenantUsuario", b =>
                {
                    b.HasOne("SGR.Api.Models.Tenant.Entities.TenantPerfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("SGR.Api.Models.Tenant.Entities.CanalVenda", b =>
                {
                    b.Navigation("FichaTecnicaCanais");
                });

            modelBuilder.Entity("SGR.Api.Models.Tenant.Entities.CategoriaInsumo", b =>
                {
                    b.Navigation("Insumos");
                });

            modelBuilder.Entity("SGR.Api.Models.Tenant.Entities.CategoriaReceita", b =>
                {
                    b.Navigation("Receitas");
                });

            modelBuilder.Entity("SGR.Api.Models.Tenant.Entities.FichaTecnica", b =>
                {
                    b.Navigation("Canais");

                    b.Navigation("Itens");
                });

            modelBuilder.Entity("SGR.Api.Models.Tenant.Entities.Receita", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("SGR.Api.Models.Tenant.Entities.TenantPerfil", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
